# Generated by Django 2.1.7 on 2019-03-12 05:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blank', models.BooleanField(default=False, verbose_name='Abrir em uma nova página')),
                ('imagem', imagekit.models.fields.ProcessedImageField(upload_to='avatars')),
            ],
        ),
    ]
