# Generated by Django 2.1.7 on 2019-03-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20190312_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='arquivo'),
        ),
    ]
