# Generated by Django 2.1.7 on 2019-03-14 04:07

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('depoimento', models.TextField()),
                ('imagem', imagekit.models.fields.ProcessedImageField(upload_to='depoimentos/%Y/%m/%d/')),
            ],
        ),
    ]
