# Generated by Django 2.1.7 on 2019-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20190307_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
