# Generated by Django 2.1.7 on 2019-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20190307_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='resumo',
            field=models.TextField(blank=True, max_length=170, null=True),
        ),
    ]
