# Generated by Django 2.1.7 on 2019-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_auto_20190307_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
