# Generated by Django 2.1.7 on 2019-03-07 22:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20190307_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
