# Generated by Django 2.1.7 on 2019-03-08 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_auto_20190307_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo'),
        ),
    ]
