# Generated by Django 2.1.7 on 2019-03-13 04:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço'},
        ),
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(upload_to='servicos/%Y/%m/%d'),
        ),
    ]
